CREATE TABLE IF NOT EXISTS UTENTE(
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nome varchar(32) NOT NULL,
cognome varchar(32) NOT NULL,
username varchar(32) NOT NULL,
password varchar(32) NOT NULL
);