CREATE TABLE IF NOT EXISTS UTENTE (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(32) NOT NULL,
    password varchar(32) NOT NULL,
    email varchar(32) NOT NULL
    );

